export const sampleStore = {
  tenant: { id: 'tenant-demo', name: 'Demo Seller', plan: 'growth' },
  store: { id: 'store-us-1', marketplace: 'US', sourceMode: 'mock' },
  costDefaults: {
    refundProvisionRate: 0.04,
    cogsPerUnit: { value: 8.4, source: 'mock_cost_upload', estimated: false },
    freightPerUnit: { value: 1.35, source: 'mock_cost_upload', estimated: false },
  },
  products: [
    {
      id: 'prod-case-001',
      asin: 'B0CASE001',
      sku: 'CASE-001',
      title: 'Shockproof Phone Case',
      price: 22.99,
      unitCost: 8.4,
      breakEvenPrice: 16.8,
      leadTimeDays: 35,
      safetyStockDays: 7,
      daysListed: 120,
      reviewCount: 58,
      returnRate7d: 0.09,
      returnRate30d: 0.04,
    },
    {
      id: 'prod-cable-002',
      asin: 'B0CABLE002',
      sku: 'CABLE-002',
      title: 'Fast Charging Cable',
      price: 12.99,
      unitCost: 5.1,
      breakEvenPrice: 9.2,
      leadTimeDays: 28,
      safetyStockDays: 7,
      daysListed: 45,
      reviewCount: 12,
      returnRate7d: 0.02,
      returnRate30d: 0.025,
    },
    {
      id: 'prod-lamp-003',
      asin: 'B0LAMP003',
      sku: 'LAMP-003',
      title: 'Desk LED Lamp',
      price: 19.99,
      unitCost: 12.5,
      breakEvenPrice: 18.4,
      leadTimeDays: 42,
      safetyStockDays: 10,
      daysListed: 260,
      reviewCount: 160,
      returnRate7d: 0.03,
      returnRate30d: 0.028,
    },
  ],
  orders: [
    {
      amazonOrderId: '111-0000001-0000001',
      productId: 'prod-case-001',
      quantity: 12,
      itemPrice: 22.99,
      amazonReferralFee: 41.38,
      fbaFulfillmentFee: 44.4,
      adCostAllocation: 39.5,
      storageFeeAllocation: 2.4,
      cogs: 100.8,
      freight: 16.2,
      paymentFee: 3.2,
    },
    {
      amazonOrderId: '111-0000002-0000002',
      productId: 'prod-cable-002',
      quantity: 20,
      itemPrice: 12.99,
      amazonReferralFee: 38.97,
      fbaFulfillmentFee: 61.0,
      adCostAllocation: 18.4,
      cogs: 102,
      freight: 18,
      paymentFee: 2.7,
    },
    {
      amazonOrderId: '111-0000003-0000003',
      productId: 'prod-lamp-003',
      quantity: 8,
      itemPrice: 19.99,
      amazonReferralFee: 23.99,
      fbaFulfillmentFee: 54.4,
      adCostAllocation: 58.2,
      storageFeeAllocation: 12.4,
      cogs: 100,
      freight: 13.2,
      paymentFee: 2.1,
    },
  ],
  inventory: [
    { productId: 'prod-case-001', available: 54, inbound: 0, avgDailySales: 12, sales7d: 84, sales30d: 350, daysInStock: 42, daysInWarehouse: 96, monthlyStorageFee: 34 },
    { productId: 'prod-cable-002', available: 480, inbound: 300, avgDailySales: 18, sales7d: 112, sales30d: 620, daysInStock: 20, daysInWarehouse: 40, monthlyStorageFee: 28 },
    { productId: 'prod-lamp-003', available: 320, inbound: 0, avgDailySales: 0.2, sales7d: 0, sales30d: 4, daysInStock: 217, daysInWarehouse: 217, monthlyStorageFee: 120 },
  ],
  adMetrics: [
    { productId: 'prod-case-001', campaignId: 'camp-case-growth', keyword: 'phone case', spend: 390, hourlySpend: 25, avgHourlySpend: 8, sales: 1800, acos: 0.216, targetAcos: 0.25, clicks30d: 260, orders30d: 78, lifecycleSignals: { daysListed: 120, reviewCount: 58, salesTrend4w: 0.24, bsrTrend4w: -0.05, inventoryDays: 4 } },
    { productId: 'prod-cable-002', campaignId: 'camp-cable-launch', keyword: 'usb c cable', spend: 210, sales: 510, acos: 0.411, targetAcos: 0.55, clicks30d: 90, orders30d: 13, lifecycleSignals: { daysListed: 45, reviewCount: 12, salesTrend4w: 0.08, bsrTrend4w: -0.02, inventoryDays: 30 } },
    { productId: 'prod-lamp-003', campaignId: 'camp-lamp-mature', keyword: 'desk lamp', spend: 430, hourlySpend: 80, avgHourlySpend: 10, sales: 460, acos: 0.935, targetAcos: 0.28, clicks30d: 48, orders30d: 0, lifecycleSignals: { daysListed: 260, reviewCount: 160, salesTrend4w: -0.18, bsrTrend4w: 0.22, inventoryDays: 999 } },
  ],
  monitorSignals: {
    'prod-case-001': { buyBoxLostMinutes: 35 },
    'prod-lamp-003': { listingChanged: true, accountHealthAtRisk: true, accountHealthReason: 'Pricing Health warning from mock signal.' },
  },
  listings: {
    'prod-case-001': { productId: 'prod-case-001', title: 'Shockproof Phone Case for iPhone', bullets: ['Slim protective case with raised camera lip', 'Soft TPU grip for everyday drops', 'Wireless charging compatible'], description: 'Everyday phone case.', images: ['main.jpg', 'side.jpg'], aPlusModules: [] },
    'prod-cable-002': { productId: 'prod-cable-002', title: 'USB C Fast Charging Cable', bullets: ['Fast charging cable for phones and tablets', 'Braided nylon design for travel', 'Includes warranty support'], description: 'Durable cable with warranty.', images: ['main.jpg', 'lifestyle.jpg', 'dimension.jpg'], aPlusModules: ['comparison'] },
    'prod-lamp-003': { productId: 'prod-lamp-003', title: 'Desk LED Lamp', bullets: ['Adjustable desk lamp', 'Multiple brightness levels'], description: 'LED lamp for desk.', images: ['main.jpg'], aPlusModules: [] },
  },
  searchTerms: [
    { productId: 'prod-case-001', term: 'phone case', impressions: 2000, conversions: 80 },
    { productId: 'prod-case-001', term: 'shockproof case', impressions: 800, conversions: 35 },
    { productId: 'prod-case-001', term: 'magsafe case', impressions: 600, conversions: 10 },
    { productId: 'prod-lamp-003', term: 'desk lamp', impressions: 1800, conversions: 12 },
    { productId: 'prod-lamp-003', term: 'led lamp', impressions: 1200, conversions: 6 },
  ],
  reviews: [
    { productId: 'prod-case-001', rating: 2, title: 'Too small', body: 'The size is a little small and the corner became loose.' },
    { productId: 'prod-case-001', rating: 5, title: 'Good protection', body: 'The case protected my phone from scratches.' },
    { productId: 'prod-lamp-003', rating: 2, title: 'Gets heat and package damaged', body: 'The package arrived damaged and the lamp gets heat after use.' },
    { productId: 'prod-lamp-003', rating: 3, title: 'Instructions confusing', body: 'Manual instructions were confusing.' },
  ],
  competitorSnapshots: {
    previous: [
      { productId: 'prod-case-001', asin: 'B0COMPCASE', price: 24.99, titleHash: 'old', dealActive: false },
      { productId: 'prod-lamp-003', asin: 'B0COMPLAMP', price: 19.99, titleHash: 'lamp-old', dealActive: false },
    ],
    current: [
      { productId: 'prod-case-001', asin: 'B0COMPCASE', price: 20.99, titleHash: 'new', dealActive: true },
      { productId: 'prod-lamp-003', asin: 'B0COMPLAMP', price: 17.99, titleHash: 'lamp-old', dealActive: false },
    ],
  },
  competitors: [
    { productId: 'prod-case-001', asin: 'B0COMPCASE', price: 20.99 },
    { productId: 'prod-lamp-003', asin: 'B0COMPLAMP', price: 17.99 },
  ],
};


